"""Nautilus LCD protocol constants.

Only the volatile JPEG operation and known hardware-mode reports are represented.
"""

CORSAIR_VID = 0x1B1C
NAUTILUS_LCD_PID = 0x0C57
NAUTILUS_INTERFACE = 0
SUPPORTED_DEVICES = frozenset({(CORSAIR_VID, NAUTILUS_LCD_PID, NAUTILUS_INTERFACE)})

DISPLAY_WIDTH = 480
DISPLAY_HEIGHT = 480

OUTPUT_REPORT_ID = 0x02
LCD_DATA_OPERATION = 0x05
OUTPUT_REPORT_SIZE = 1024
OUTPUT_HEADER_SIZE = 8
PAYLOAD_SIZE = OUTPUT_REPORT_SIZE - OUTPUT_HEADER_SIZE
MAX_PACKET_INDEX = 0xFF
MAX_REPORTS = MAX_PACKET_INDEX + 1

MAX_JPEG_BYTES = MAX_REPORTS * PAYLOAD_SIZE

FIRMWARE_REPORT_ID = 0x05
FEATURE_REPORT_SIZE = 33
