"""Public compatibility documentation generated from the read-only catalog."""

from __future__ import annotations

from collections import defaultdict

from .catalog import HARDWARE_CATALOG
from .models import ControlSupport, HardwareIdentity


STATUS_TITLES = {
    ControlSupport.SUPPORTED: "Supported",
    ControlSupport.EXPERIMENTAL: "Experimental control",
    ControlSupport.PROTOCOL_KNOWN_UNIMPLEMENTED: "Protocol known but unimplemented",
    ControlSupport.IDENTIFICATION_ONLY: "Identification only",
    ControlSupport.UNSUPPORTED: "Unsupported",
}


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _panel(record: HardwareIdentity) -> str:
    if record.panel_width is None or record.panel_height is None:
        return "Unknown"
    return f"{record.panel_width}×{record.panel_height}"


def render_hardware_compatibility() -> str:
    """Render the tracked compatibility page from immutable catalog records."""
    groups: dict[ControlSupport, list[HardwareIdentity]] = defaultdict(list)
    for record in HARDWARE_CATALOG:
        groups[record.control_support].append(record)

    lines = [
        "# Hardware compatibility status",
        "",
        "<!-- Generated by scripts/generate_hardware_compatibility.py; do not edit manually. -->",
        "",
        "This page reflects NautiBoy's hardware catalog. **Identification does not imply control",
        "support or authorize hardware writes.** A VID:PID match may provide a friendly name while",
        "configuration remains unavailable.",
        "",
        "Only devices in **Supported** have an enabled native NautiBoy control adapter. All other",
        "records are read-only knowledge used for recognition and future compatibility research.",
        "Unknown fields remain unknown rather than being inferred from related products.",
        "",
    ]
    for status in ControlSupport:
        records = groups.get(status, [])
        if not records:
            continue
        lines.extend([
            f"## {STATUS_TITLES[status]}",
            "",
            "| Manufacturer | Device/family | VID:PID | Panel | Confidence | Notes |",
            "|---|---|---|---:|---|---|",
        ])
        for record in records:
            lines.append(
                f"| {_cell(record.vendor)} | {_cell(record.model)} | `{record.vid:04x}:{record.pid:04x}` "
                f"| {_panel(record)} | `{record.confidence.value}` | {_cell(record.notes or '—')} |"
            )
        lines.append("")
    lines.extend([
        "## Help expand compatibility",
        "",
        "If a device is unsupported, unknown, or detected incorrectly, click **CHECK MY HARDWARE**",
        "in the main window (or open **Settings → Generate Hardware Report**). Review the complete",
        "text and JSON preview, save the ZIP locally, and",
        "email it yourself to **hardware@nautiboy.dev** with the device's marketed model name.",
        "NautiBoy never uploads or emails reports automatically and report generation performs no",
        "network activity or hardware writes.",
        "",
        "For implementation evidence and pinned research revisions, see",
        "[Hardware knowledge base](hardware-knowledge-base.md).",
        "",
    ])
    return "\n".join(lines)
